// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CustomerSupport.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CustomerSupport {

  /// <summary>Holder for reflection information generated from CustomerSupport.proto</summary>
  public static partial class CustomerSupportReflection {

    #region Descriptor
    /// <summary>File descriptor for CustomerSupport.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CustomerSupportReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVDdXN0b21lclN1cHBvcnQucHJvdG8SD0N1c3RvbWVyU3VwcG9ydCJPChJS",
            "ZXN0b3JlVXNlclJlcXVlc3QSEwoLZGVsZXRlZERhdGUYASABKAMSEQoJdXNl",
            "ck5hbWVzGAMgAygJEhEKCXJlcXVlc3RlchgEIAEoCSLBAQoYUmVzdG9yZUVu",
            "dGVycHJpc2VSZXF1ZXN0EhMKC2RlbGV0ZWREYXRlGAEgASgDEhYKDmVudGVy",
            "cHJpc2VOYW1lGAIgASgJEhQKDGNvbnRhY3RFbWFpbBgDIAEoCRIUCgxlbnRl",
            "cnByaXNlSWQYBCABKAUSOQoOZW50ZXJwcmlzZVR5cGUYBSABKA4yIS5DdXN0",
            "b21lclN1cHBvcnQuQ1NFbnRlcnByaXNlVHlwZRIRCglyZXF1ZXN0ZXIYBiAB",
            "KAkiUAoSVXBkYXRlQWxpYXNSZXF1ZXN0EicKB2FsaWFzZXMYASADKAsyFi5D",
            "dXN0b21lclN1cHBvcnQuQWxpYXMSEQoJcmVxdWVzdGVyGAIgASgJImwKBUFs",
            "aWFzEhAKCHVzZXJOYW1lGAEgASgJEg0KBWFsaWFzGAIgASgJEhUKDWlzRW1h",
            "aWxDaGFuZ2UYAyABKAgSGAoQaXNSZW1vdmVPbGRFbWFpbBgEIAEoCBIRCglu",
            "ZXdEb21haW4YBSABKAkigQEKF0N1c3RvbWVyU3VwcG9ydFJlc3BvbnNlEgwK",
            "BGRhdGUYASABKAMSEAoIcmVnaW9uSWQYAiABKAUSLgoGc3RhdHVzGAMgASgO",
            "Mh4uQ3VzdG9tZXJTdXBwb3J0LlNlcnZpY2VTdGF0dXMSFgoOYWRkaXRpb25h",
            "bEluZm8YBCABKAkiRgodVXBkYXRlRW50ZXJwcmlzZURvbWFpblJlcXVlc3QS",
            "FAoMZW50ZXJwcmlzZUlkGAEgASgFEg8KB0RvbWFpbnMYAiADKAkiMgoaQ2xl",
            "YXJEZXZpY2VBcHByb3ZhbFJlcXVlc3QSFAoMZW50ZXJwcmlzZUlkGAEgASgF",
            "KisKEENTRW50ZXJwcmlzZVR5cGUSDgoKZW50ZXJwcmlzZRAAEgcKA3NzbxAB",
            "KnEKEERCUmVjb3ZlcnlTdGF0dXMSDQoJVW5kZWZpbmVkEAASDAoIQ3JlYXRp",
            "bmcQARINCglBdmFpbGFibGUQAhIMCghEZWxldGluZxADEgsKB0RlbGV0ZWQQ",
            "BBIKCgZGYWlsZWQQBRIKCgZMb2NrZWQQBipJCg1TZXJ2aWNlU3RhdHVzEgsK",
            "B1N1Y2Nlc3MQABILCgdBYm9ydGVkEAESEQoNTm90X0F2YWlsYWJsZRACEgsK",
            "B0lnbm9yZWQQA0IrChhjb20ua2VlcGVyc2VjdXJpdHkucHJvdG9CD0N1c3Rv",
            "bWVyU3VwcG9ydGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CustomerSupport.CSEnterpriseType), typeof(global::CustomerSupport.DBRecoveryStatus), typeof(global::CustomerSupport.ServiceStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CustomerSupport.RestoreUserRequest), global::CustomerSupport.RestoreUserRequest.Parser, new[]{ "DeletedDate", "UserNames", "Requester" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CustomerSupport.RestoreEnterpriseRequest), global::CustomerSupport.RestoreEnterpriseRequest.Parser, new[]{ "DeletedDate", "EnterpriseName", "ContactEmail", "EnterpriseId", "EnterpriseType", "Requester" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CustomerSupport.UpdateAliasRequest), global::CustomerSupport.UpdateAliasRequest.Parser, new[]{ "Aliases", "Requester" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CustomerSupport.Alias), global::CustomerSupport.Alias.Parser, new[]{ "UserName", "Alias_", "IsEmailChange", "IsRemoveOldEmail", "NewDomain" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CustomerSupport.CustomerSupportResponse), global::CustomerSupport.CustomerSupportResponse.Parser, new[]{ "Date", "RegionId", "Status", "AdditionalInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CustomerSupport.UpdateEnterpriseDomainRequest), global::CustomerSupport.UpdateEnterpriseDomainRequest.Parser, new[]{ "EnterpriseId", "Domains" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CustomerSupport.ClearDeviceApprovalRequest), global::CustomerSupport.ClearDeviceApprovalRequest.Parser, new[]{ "EnterpriseId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CSEnterpriseType {
    [pbr::OriginalName("enterprise")] Enterprise = 0,
    [pbr::OriginalName("sso")] Sso = 1,
  }

  public enum DBRecoveryStatus {
    [pbr::OriginalName("Undefined")] Undefined = 0,
    [pbr::OriginalName("Creating")] Creating = 1,
    [pbr::OriginalName("Available")] Available = 2,
    [pbr::OriginalName("Deleting")] Deleting = 3,
    [pbr::OriginalName("Deleted")] Deleted = 4,
    [pbr::OriginalName("Failed")] Failed = 5,
    [pbr::OriginalName("Locked")] Locked = 6,
  }

  public enum ServiceStatus {
    [pbr::OriginalName("Success")] Success = 0,
    [pbr::OriginalName("Aborted")] Aborted = 1,
    [pbr::OriginalName("Not_Available")] NotAvailable = 2,
    [pbr::OriginalName("Ignored")] Ignored = 3,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RestoreUserRequest : pb::IMessage<RestoreUserRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RestoreUserRequest> _parser = new pb::MessageParser<RestoreUserRequest>(() => new RestoreUserRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RestoreUserRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CustomerSupport.CustomerSupportReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RestoreUserRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RestoreUserRequest(RestoreUserRequest other) : this() {
      deletedDate_ = other.deletedDate_;
      userNames_ = other.userNames_.Clone();
      requester_ = other.requester_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RestoreUserRequest Clone() {
      return new RestoreUserRequest(this);
    }

    /// <summary>Field number for the "deletedDate" field.</summary>
    public const int DeletedDateFieldNumber = 1;
    private long deletedDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DeletedDate {
      get { return deletedDate_; }
      set {
        deletedDate_ = value;
      }
    }

    /// <summary>Field number for the "userNames" field.</summary>
    public const int UserNamesFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_userNames_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> userNames_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> UserNames {
      get { return userNames_; }
    }

    /// <summary>Field number for the "requester" field.</summary>
    public const int RequesterFieldNumber = 4;
    private string requester_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Requester {
      get { return requester_; }
      set {
        requester_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RestoreUserRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RestoreUserRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DeletedDate != other.DeletedDate) return false;
      if(!userNames_.Equals(other.userNames_)) return false;
      if (Requester != other.Requester) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DeletedDate != 0L) hash ^= DeletedDate.GetHashCode();
      hash ^= userNames_.GetHashCode();
      if (Requester.Length != 0) hash ^= Requester.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DeletedDate != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(DeletedDate);
      }
      userNames_.WriteTo(output, _repeated_userNames_codec);
      if (Requester.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Requester);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DeletedDate != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(DeletedDate);
      }
      userNames_.WriteTo(ref output, _repeated_userNames_codec);
      if (Requester.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Requester);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DeletedDate != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DeletedDate);
      }
      size += userNames_.CalculateSize(_repeated_userNames_codec);
      if (Requester.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Requester);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RestoreUserRequest other) {
      if (other == null) {
        return;
      }
      if (other.DeletedDate != 0L) {
        DeletedDate = other.DeletedDate;
      }
      userNames_.Add(other.userNames_);
      if (other.Requester.Length != 0) {
        Requester = other.Requester;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DeletedDate = input.ReadInt64();
            break;
          }
          case 26: {
            userNames_.AddEntriesFrom(input, _repeated_userNames_codec);
            break;
          }
          case 34: {
            Requester = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DeletedDate = input.ReadInt64();
            break;
          }
          case 26: {
            userNames_.AddEntriesFrom(ref input, _repeated_userNames_codec);
            break;
          }
          case 34: {
            Requester = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RestoreEnterpriseRequest : pb::IMessage<RestoreEnterpriseRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RestoreEnterpriseRequest> _parser = new pb::MessageParser<RestoreEnterpriseRequest>(() => new RestoreEnterpriseRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RestoreEnterpriseRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CustomerSupport.CustomerSupportReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RestoreEnterpriseRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RestoreEnterpriseRequest(RestoreEnterpriseRequest other) : this() {
      deletedDate_ = other.deletedDate_;
      enterpriseName_ = other.enterpriseName_;
      contactEmail_ = other.contactEmail_;
      enterpriseId_ = other.enterpriseId_;
      enterpriseType_ = other.enterpriseType_;
      requester_ = other.requester_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RestoreEnterpriseRequest Clone() {
      return new RestoreEnterpriseRequest(this);
    }

    /// <summary>Field number for the "deletedDate" field.</summary>
    public const int DeletedDateFieldNumber = 1;
    private long deletedDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DeletedDate {
      get { return deletedDate_; }
      set {
        deletedDate_ = value;
      }
    }

    /// <summary>Field number for the "enterpriseName" field.</summary>
    public const int EnterpriseNameFieldNumber = 2;
    private string enterpriseName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string EnterpriseName {
      get { return enterpriseName_; }
      set {
        enterpriseName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contactEmail" field.</summary>
    public const int ContactEmailFieldNumber = 3;
    private string contactEmail_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ContactEmail {
      get { return contactEmail_; }
      set {
        contactEmail_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "enterpriseId" field.</summary>
    public const int EnterpriseIdFieldNumber = 4;
    private int enterpriseId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EnterpriseId {
      get { return enterpriseId_; }
      set {
        enterpriseId_ = value;
      }
    }

    /// <summary>Field number for the "enterpriseType" field.</summary>
    public const int EnterpriseTypeFieldNumber = 5;
    private global::CustomerSupport.CSEnterpriseType enterpriseType_ = global::CustomerSupport.CSEnterpriseType.Enterprise;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CustomerSupport.CSEnterpriseType EnterpriseType {
      get { return enterpriseType_; }
      set {
        enterpriseType_ = value;
      }
    }

    /// <summary>Field number for the "requester" field.</summary>
    public const int RequesterFieldNumber = 6;
    private string requester_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Requester {
      get { return requester_; }
      set {
        requester_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RestoreEnterpriseRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RestoreEnterpriseRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DeletedDate != other.DeletedDate) return false;
      if (EnterpriseName != other.EnterpriseName) return false;
      if (ContactEmail != other.ContactEmail) return false;
      if (EnterpriseId != other.EnterpriseId) return false;
      if (EnterpriseType != other.EnterpriseType) return false;
      if (Requester != other.Requester) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (DeletedDate != 0L) hash ^= DeletedDate.GetHashCode();
      if (EnterpriseName.Length != 0) hash ^= EnterpriseName.GetHashCode();
      if (ContactEmail.Length != 0) hash ^= ContactEmail.GetHashCode();
      if (EnterpriseId != 0) hash ^= EnterpriseId.GetHashCode();
      if (EnterpriseType != global::CustomerSupport.CSEnterpriseType.Enterprise) hash ^= EnterpriseType.GetHashCode();
      if (Requester.Length != 0) hash ^= Requester.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (DeletedDate != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(DeletedDate);
      }
      if (EnterpriseName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EnterpriseName);
      }
      if (ContactEmail.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ContactEmail);
      }
      if (EnterpriseId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(EnterpriseId);
      }
      if (EnterpriseType != global::CustomerSupport.CSEnterpriseType.Enterprise) {
        output.WriteRawTag(40);
        output.WriteEnum((int) EnterpriseType);
      }
      if (Requester.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Requester);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (DeletedDate != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(DeletedDate);
      }
      if (EnterpriseName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(EnterpriseName);
      }
      if (ContactEmail.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ContactEmail);
      }
      if (EnterpriseId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(EnterpriseId);
      }
      if (EnterpriseType != global::CustomerSupport.CSEnterpriseType.Enterprise) {
        output.WriteRawTag(40);
        output.WriteEnum((int) EnterpriseType);
      }
      if (Requester.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Requester);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (DeletedDate != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DeletedDate);
      }
      if (EnterpriseName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EnterpriseName);
      }
      if (ContactEmail.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactEmail);
      }
      if (EnterpriseId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EnterpriseId);
      }
      if (EnterpriseType != global::CustomerSupport.CSEnterpriseType.Enterprise) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EnterpriseType);
      }
      if (Requester.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Requester);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RestoreEnterpriseRequest other) {
      if (other == null) {
        return;
      }
      if (other.DeletedDate != 0L) {
        DeletedDate = other.DeletedDate;
      }
      if (other.EnterpriseName.Length != 0) {
        EnterpriseName = other.EnterpriseName;
      }
      if (other.ContactEmail.Length != 0) {
        ContactEmail = other.ContactEmail;
      }
      if (other.EnterpriseId != 0) {
        EnterpriseId = other.EnterpriseId;
      }
      if (other.EnterpriseType != global::CustomerSupport.CSEnterpriseType.Enterprise) {
        EnterpriseType = other.EnterpriseType;
      }
      if (other.Requester.Length != 0) {
        Requester = other.Requester;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DeletedDate = input.ReadInt64();
            break;
          }
          case 18: {
            EnterpriseName = input.ReadString();
            break;
          }
          case 26: {
            ContactEmail = input.ReadString();
            break;
          }
          case 32: {
            EnterpriseId = input.ReadInt32();
            break;
          }
          case 40: {
            EnterpriseType = (global::CustomerSupport.CSEnterpriseType) input.ReadEnum();
            break;
          }
          case 50: {
            Requester = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            DeletedDate = input.ReadInt64();
            break;
          }
          case 18: {
            EnterpriseName = input.ReadString();
            break;
          }
          case 26: {
            ContactEmail = input.ReadString();
            break;
          }
          case 32: {
            EnterpriseId = input.ReadInt32();
            break;
          }
          case 40: {
            EnterpriseType = (global::CustomerSupport.CSEnterpriseType) input.ReadEnum();
            break;
          }
          case 50: {
            Requester = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateAliasRequest : pb::IMessage<UpdateAliasRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateAliasRequest> _parser = new pb::MessageParser<UpdateAliasRequest>(() => new UpdateAliasRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateAliasRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CustomerSupport.CustomerSupportReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateAliasRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateAliasRequest(UpdateAliasRequest other) : this() {
      aliases_ = other.aliases_.Clone();
      requester_ = other.requester_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateAliasRequest Clone() {
      return new UpdateAliasRequest(this);
    }

    /// <summary>Field number for the "aliases" field.</summary>
    public const int AliasesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CustomerSupport.Alias> _repeated_aliases_codec
        = pb::FieldCodec.ForMessage(10, global::CustomerSupport.Alias.Parser);
    private readonly pbc::RepeatedField<global::CustomerSupport.Alias> aliases_ = new pbc::RepeatedField<global::CustomerSupport.Alias>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CustomerSupport.Alias> Aliases {
      get { return aliases_; }
    }

    /// <summary>Field number for the "requester" field.</summary>
    public const int RequesterFieldNumber = 2;
    private string requester_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Requester {
      get { return requester_; }
      set {
        requester_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateAliasRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateAliasRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!aliases_.Equals(other.aliases_)) return false;
      if (Requester != other.Requester) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= aliases_.GetHashCode();
      if (Requester.Length != 0) hash ^= Requester.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      aliases_.WriteTo(output, _repeated_aliases_codec);
      if (Requester.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Requester);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      aliases_.WriteTo(ref output, _repeated_aliases_codec);
      if (Requester.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Requester);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += aliases_.CalculateSize(_repeated_aliases_codec);
      if (Requester.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Requester);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateAliasRequest other) {
      if (other == null) {
        return;
      }
      aliases_.Add(other.aliases_);
      if (other.Requester.Length != 0) {
        Requester = other.Requester;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            aliases_.AddEntriesFrom(input, _repeated_aliases_codec);
            break;
          }
          case 18: {
            Requester = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            aliases_.AddEntriesFrom(ref input, _repeated_aliases_codec);
            break;
          }
          case 18: {
            Requester = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Alias : pb::IMessage<Alias>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Alias> _parser = new pb::MessageParser<Alias>(() => new Alias());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Alias> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CustomerSupport.CustomerSupportReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Alias() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Alias(Alias other) : this() {
      userName_ = other.userName_;
      alias_ = other.alias_;
      isEmailChange_ = other.isEmailChange_;
      isRemoveOldEmail_ = other.isRemoveOldEmail_;
      newDomain_ = other.newDomain_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Alias Clone() {
      return new Alias(this);
    }

    /// <summary>Field number for the "userName" field.</summary>
    public const int UserNameFieldNumber = 1;
    private string userName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserName {
      get { return userName_; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "alias" field.</summary>
    public const int Alias_FieldNumber = 2;
    private string alias_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Alias_ {
      get { return alias_; }
      set {
        alias_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isEmailChange" field.</summary>
    public const int IsEmailChangeFieldNumber = 3;
    private bool isEmailChange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsEmailChange {
      get { return isEmailChange_; }
      set {
        isEmailChange_ = value;
      }
    }

    /// <summary>Field number for the "isRemoveOldEmail" field.</summary>
    public const int IsRemoveOldEmailFieldNumber = 4;
    private bool isRemoveOldEmail_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRemoveOldEmail {
      get { return isRemoveOldEmail_; }
      set {
        isRemoveOldEmail_ = value;
      }
    }

    /// <summary>Field number for the "newDomain" field.</summary>
    public const int NewDomainFieldNumber = 5;
    private string newDomain_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NewDomain {
      get { return newDomain_; }
      set {
        newDomain_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Alias);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Alias other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UserName != other.UserName) return false;
      if (Alias_ != other.Alias_) return false;
      if (IsEmailChange != other.IsEmailChange) return false;
      if (IsRemoveOldEmail != other.IsRemoveOldEmail) return false;
      if (NewDomain != other.NewDomain) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UserName.Length != 0) hash ^= UserName.GetHashCode();
      if (Alias_.Length != 0) hash ^= Alias_.GetHashCode();
      if (IsEmailChange != false) hash ^= IsEmailChange.GetHashCode();
      if (IsRemoveOldEmail != false) hash ^= IsRemoveOldEmail.GetHashCode();
      if (NewDomain.Length != 0) hash ^= NewDomain.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UserName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserName);
      }
      if (Alias_.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Alias_);
      }
      if (IsEmailChange != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsEmailChange);
      }
      if (IsRemoveOldEmail != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsRemoveOldEmail);
      }
      if (NewDomain.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NewDomain);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UserName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UserName);
      }
      if (Alias_.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Alias_);
      }
      if (IsEmailChange != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsEmailChange);
      }
      if (IsRemoveOldEmail != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsRemoveOldEmail);
      }
      if (NewDomain.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NewDomain);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UserName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (Alias_.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Alias_);
      }
      if (IsEmailChange != false) {
        size += 1 + 1;
      }
      if (IsRemoveOldEmail != false) {
        size += 1 + 1;
      }
      if (NewDomain.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NewDomain);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Alias other) {
      if (other == null) {
        return;
      }
      if (other.UserName.Length != 0) {
        UserName = other.UserName;
      }
      if (other.Alias_.Length != 0) {
        Alias_ = other.Alias_;
      }
      if (other.IsEmailChange != false) {
        IsEmailChange = other.IsEmailChange;
      }
      if (other.IsRemoveOldEmail != false) {
        IsRemoveOldEmail = other.IsRemoveOldEmail;
      }
      if (other.NewDomain.Length != 0) {
        NewDomain = other.NewDomain;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UserName = input.ReadString();
            break;
          }
          case 18: {
            Alias_ = input.ReadString();
            break;
          }
          case 24: {
            IsEmailChange = input.ReadBool();
            break;
          }
          case 32: {
            IsRemoveOldEmail = input.ReadBool();
            break;
          }
          case 42: {
            NewDomain = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            UserName = input.ReadString();
            break;
          }
          case 18: {
            Alias_ = input.ReadString();
            break;
          }
          case 24: {
            IsEmailChange = input.ReadBool();
            break;
          }
          case 32: {
            IsRemoveOldEmail = input.ReadBool();
            break;
          }
          case 42: {
            NewDomain = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CustomerSupportResponse : pb::IMessage<CustomerSupportResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CustomerSupportResponse> _parser = new pb::MessageParser<CustomerSupportResponse>(() => new CustomerSupportResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CustomerSupportResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CustomerSupport.CustomerSupportReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomerSupportResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomerSupportResponse(CustomerSupportResponse other) : this() {
      date_ = other.date_;
      regionId_ = other.regionId_;
      status_ = other.status_;
      additionalInfo_ = other.additionalInfo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CustomerSupportResponse Clone() {
      return new CustomerSupportResponse(this);
    }

    /// <summary>Field number for the "date" field.</summary>
    public const int DateFieldNumber = 1;
    private long date_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Date {
      get { return date_; }
      set {
        date_ = value;
      }
    }

    /// <summary>Field number for the "regionId" field.</summary>
    public const int RegionIdFieldNumber = 2;
    private int regionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RegionId {
      get { return regionId_; }
      set {
        regionId_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 3;
    private global::CustomerSupport.ServiceStatus status_ = global::CustomerSupport.ServiceStatus.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CustomerSupport.ServiceStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "additionalInfo" field.</summary>
    public const int AdditionalInfoFieldNumber = 4;
    private string additionalInfo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AdditionalInfo {
      get { return additionalInfo_; }
      set {
        additionalInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CustomerSupportResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CustomerSupportResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Date != other.Date) return false;
      if (RegionId != other.RegionId) return false;
      if (Status != other.Status) return false;
      if (AdditionalInfo != other.AdditionalInfo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Date != 0L) hash ^= Date.GetHashCode();
      if (RegionId != 0) hash ^= RegionId.GetHashCode();
      if (Status != global::CustomerSupport.ServiceStatus.Success) hash ^= Status.GetHashCode();
      if (AdditionalInfo.Length != 0) hash ^= AdditionalInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Date != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Date);
      }
      if (RegionId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RegionId);
      }
      if (Status != global::CustomerSupport.ServiceStatus.Success) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (AdditionalInfo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AdditionalInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Date != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Date);
      }
      if (RegionId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RegionId);
      }
      if (Status != global::CustomerSupport.ServiceStatus.Success) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Status);
      }
      if (AdditionalInfo.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AdditionalInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Date != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Date);
      }
      if (RegionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RegionId);
      }
      if (Status != global::CustomerSupport.ServiceStatus.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (AdditionalInfo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AdditionalInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CustomerSupportResponse other) {
      if (other == null) {
        return;
      }
      if (other.Date != 0L) {
        Date = other.Date;
      }
      if (other.RegionId != 0) {
        RegionId = other.RegionId;
      }
      if (other.Status != global::CustomerSupport.ServiceStatus.Success) {
        Status = other.Status;
      }
      if (other.AdditionalInfo.Length != 0) {
        AdditionalInfo = other.AdditionalInfo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Date = input.ReadInt64();
            break;
          }
          case 16: {
            RegionId = input.ReadInt32();
            break;
          }
          case 24: {
            Status = (global::CustomerSupport.ServiceStatus) input.ReadEnum();
            break;
          }
          case 34: {
            AdditionalInfo = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Date = input.ReadInt64();
            break;
          }
          case 16: {
            RegionId = input.ReadInt32();
            break;
          }
          case 24: {
            Status = (global::CustomerSupport.ServiceStatus) input.ReadEnum();
            break;
          }
          case 34: {
            AdditionalInfo = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpdateEnterpriseDomainRequest : pb::IMessage<UpdateEnterpriseDomainRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdateEnterpriseDomainRequest> _parser = new pb::MessageParser<UpdateEnterpriseDomainRequest>(() => new UpdateEnterpriseDomainRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpdateEnterpriseDomainRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CustomerSupport.CustomerSupportReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateEnterpriseDomainRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateEnterpriseDomainRequest(UpdateEnterpriseDomainRequest other) : this() {
      enterpriseId_ = other.enterpriseId_;
      domains_ = other.domains_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpdateEnterpriseDomainRequest Clone() {
      return new UpdateEnterpriseDomainRequest(this);
    }

    /// <summary>Field number for the "enterpriseId" field.</summary>
    public const int EnterpriseIdFieldNumber = 1;
    private int enterpriseId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EnterpriseId {
      get { return enterpriseId_; }
      set {
        enterpriseId_ = value;
      }
    }

    /// <summary>Field number for the "Domains" field.</summary>
    public const int DomainsFieldNumber = 2;
    private static readonly pb::FieldCodec<string> _repeated_domains_codec
        = pb::FieldCodec.ForString(18);
    private readonly pbc::RepeatedField<string> domains_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Domains {
      get { return domains_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpdateEnterpriseDomainRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpdateEnterpriseDomainRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EnterpriseId != other.EnterpriseId) return false;
      if(!domains_.Equals(other.domains_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EnterpriseId != 0) hash ^= EnterpriseId.GetHashCode();
      hash ^= domains_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EnterpriseId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EnterpriseId);
      }
      domains_.WriteTo(output, _repeated_domains_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EnterpriseId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EnterpriseId);
      }
      domains_.WriteTo(ref output, _repeated_domains_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EnterpriseId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EnterpriseId);
      }
      size += domains_.CalculateSize(_repeated_domains_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpdateEnterpriseDomainRequest other) {
      if (other == null) {
        return;
      }
      if (other.EnterpriseId != 0) {
        EnterpriseId = other.EnterpriseId;
      }
      domains_.Add(other.domains_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EnterpriseId = input.ReadInt32();
            break;
          }
          case 18: {
            domains_.AddEntriesFrom(input, _repeated_domains_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EnterpriseId = input.ReadInt32();
            break;
          }
          case 18: {
            domains_.AddEntriesFrom(ref input, _repeated_domains_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClearDeviceApprovalRequest : pb::IMessage<ClearDeviceApprovalRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClearDeviceApprovalRequest> _parser = new pb::MessageParser<ClearDeviceApprovalRequest>(() => new ClearDeviceApprovalRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClearDeviceApprovalRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CustomerSupport.CustomerSupportReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClearDeviceApprovalRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClearDeviceApprovalRequest(ClearDeviceApprovalRequest other) : this() {
      enterpriseId_ = other.enterpriseId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClearDeviceApprovalRequest Clone() {
      return new ClearDeviceApprovalRequest(this);
    }

    /// <summary>Field number for the "enterpriseId" field.</summary>
    public const int EnterpriseIdFieldNumber = 1;
    private int enterpriseId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int EnterpriseId {
      get { return enterpriseId_; }
      set {
        enterpriseId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClearDeviceApprovalRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClearDeviceApprovalRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EnterpriseId != other.EnterpriseId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EnterpriseId != 0) hash ^= EnterpriseId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EnterpriseId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EnterpriseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EnterpriseId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EnterpriseId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EnterpriseId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EnterpriseId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClearDeviceApprovalRequest other) {
      if (other == null) {
        return;
      }
      if (other.EnterpriseId != 0) {
        EnterpriseId = other.EnterpriseId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EnterpriseId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EnterpriseId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
