// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: upsell.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Upsell {

  /// <summary>Holder for reflection information generated from upsell.proto</summary>
  public static partial class UpsellReflection {

    #region Descriptor
    /// <summary>File descriptor for upsell.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UpsellReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgx1cHNlbGwucHJvdG8SBlVwc2VsbCJdCg1VcHNlbGxSZXF1ZXN0Eg0KBWVt",
            "YWlsGAEgASgJEg4KBmxvY2FsZRgCIAEoCRIWCg5jbGllbnRfdmVyc2lvbhgD",
            "IAEoCRIVCg1zZXNzaW9uX3Rva2VuGAQgASgJIjwKDlVwc2VsbFJlc3BvbnNl",
            "EioKDFVwc2VsbEJhbm5lchgBIAMoCzIULlVwc2VsbC5VcHNlbGxCYW5uZXIi",
            "uQEKDFVwc2VsbEJhbm5lchIRCgliYW5uZXJfaWQYASABKAUSGAoQYmFubmVy",
            "X29rX2FjdGlvbhgCIAEoCRIYChBiYW5uZXJfb2tfYnV0dG9uGAMgASgJEhwK",
            "FGJhbm5lcl9jYW5jZWxfYWN0aW9uGAQgASgJEhwKFGJhbm5lcl9jYW5jZWxf",
            "YnV0dG9uGAUgASgJEhYKDmJhbm5lcl9tZXNzYWdlGAYgASgJEg4KBmxvY2Fs",
            "ZRgHIAEoCSpfCgpDbGllbnRUeXBlEhcKE0RFRkFVTFRfQ0xJRU5UX1RZUEUQ",
            "ABIHCgNBTEwQARILCgdBTkRST0lEEAISBwoDSU9TEAMSDQoJTUlDUk9TT0ZU",
            "EAQSCgoGV0VCQVBQEAUqVwoNQ2xpZW50VmVyc2lvbhITCg9ERUZBVUxUX1ZF",
            "UlNJT04QABIQCgxTVVBQT1JUU19BTEwQARIPCgtCQVNFVkVSU0lPThAOEg4K",
            "CkFCT1ZFUkFOR0UQD0IiChhjb20ua2VlcGVyc2VjdXJpdHkucHJvdG9CBlVw",
            "c2VsbGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Upsell.ClientType), typeof(global::Upsell.ClientVersion), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Upsell.UpsellRequest), global::Upsell.UpsellRequest.Parser, new[]{ "Email", "Locale", "ClientVersion", "SessionToken" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Upsell.UpsellResponse), global::Upsell.UpsellResponse.Parser, new[]{ "UpsellBanner" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Upsell.UpsellBanner), global::Upsell.UpsellBanner.Parser, new[]{ "BannerId", "BannerOkAction", "BannerOkButton", "BannerCancelAction", "BannerCancelButton", "BannerMessage", "Locale" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ClientType {
    [pbr::OriginalName("DEFAULT_CLIENT_TYPE")] DefaultClientType = 0,
    [pbr::OriginalName("ALL")] All = 1,
    [pbr::OriginalName("ANDROID")] Android = 2,
    [pbr::OriginalName("IOS")] Ios = 3,
    [pbr::OriginalName("MICROSOFT")] Microsoft = 4,
    [pbr::OriginalName("WEBAPP")] Webapp = 5,
  }

  public enum ClientVersion {
    [pbr::OriginalName("DEFAULT_VERSION")] DefaultVersion = 0,
    [pbr::OriginalName("SUPPORTS_ALL")] SupportsAll = 1,
    [pbr::OriginalName("BASEVERSION")] Baseversion = 14,
    [pbr::OriginalName("ABOVERANGE")] Aboverange = 15,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpsellRequest : pb::IMessage<UpsellRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpsellRequest> _parser = new pb::MessageParser<UpsellRequest>(() => new UpsellRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpsellRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Upsell.UpsellReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpsellRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpsellRequest(UpsellRequest other) : this() {
      email_ = other.email_;
      locale_ = other.locale_;
      clientVersion_ = other.clientVersion_;
      sessionToken_ = other.sessionToken_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpsellRequest Clone() {
      return new UpsellRequest(this);
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 1;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locale" field.</summary>
    public const int LocaleFieldNumber = 2;
    private string locale_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Locale {
      get { return locale_; }
      set {
        locale_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "client_version" field.</summary>
    public const int ClientVersionFieldNumber = 3;
    private string clientVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ClientVersion {
      get { return clientVersion_; }
      set {
        clientVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "session_token" field.</summary>
    public const int SessionTokenFieldNumber = 4;
    private string sessionToken_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SessionToken {
      get { return sessionToken_; }
      set {
        sessionToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpsellRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpsellRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Email != other.Email) return false;
      if (Locale != other.Locale) return false;
      if (ClientVersion != other.ClientVersion) return false;
      if (SessionToken != other.SessionToken) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Locale.Length != 0) hash ^= Locale.GetHashCode();
      if (ClientVersion.Length != 0) hash ^= ClientVersion.GetHashCode();
      if (SessionToken.Length != 0) hash ^= SessionToken.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Locale.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Locale);
      }
      if (ClientVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ClientVersion);
      }
      if (SessionToken.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SessionToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Email.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Email);
      }
      if (Locale.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Locale);
      }
      if (ClientVersion.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ClientVersion);
      }
      if (SessionToken.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(SessionToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Locale.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Locale);
      }
      if (ClientVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientVersion);
      }
      if (SessionToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionToken);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpsellRequest other) {
      if (other == null) {
        return;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Locale.Length != 0) {
        Locale = other.Locale;
      }
      if (other.ClientVersion.Length != 0) {
        ClientVersion = other.ClientVersion;
      }
      if (other.SessionToken.Length != 0) {
        SessionToken = other.SessionToken;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Locale = input.ReadString();
            break;
          }
          case 26: {
            ClientVersion = input.ReadString();
            break;
          }
          case 34: {
            SessionToken = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Email = input.ReadString();
            break;
          }
          case 18: {
            Locale = input.ReadString();
            break;
          }
          case 26: {
            ClientVersion = input.ReadString();
            break;
          }
          case 34: {
            SessionToken = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpsellResponse : pb::IMessage<UpsellResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpsellResponse> _parser = new pb::MessageParser<UpsellResponse>(() => new UpsellResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpsellResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Upsell.UpsellReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpsellResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpsellResponse(UpsellResponse other) : this() {
      upsellBanner_ = other.upsellBanner_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpsellResponse Clone() {
      return new UpsellResponse(this);
    }

    /// <summary>Field number for the "UpsellBanner" field.</summary>
    public const int UpsellBannerFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Upsell.UpsellBanner> _repeated_upsellBanner_codec
        = pb::FieldCodec.ForMessage(10, global::Upsell.UpsellBanner.Parser);
    private readonly pbc::RepeatedField<global::Upsell.UpsellBanner> upsellBanner_ = new pbc::RepeatedField<global::Upsell.UpsellBanner>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Upsell.UpsellBanner> UpsellBanner {
      get { return upsellBanner_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpsellResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpsellResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!upsellBanner_.Equals(other.upsellBanner_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= upsellBanner_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      upsellBanner_.WriteTo(output, _repeated_upsellBanner_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      upsellBanner_.WriteTo(ref output, _repeated_upsellBanner_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += upsellBanner_.CalculateSize(_repeated_upsellBanner_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpsellResponse other) {
      if (other == null) {
        return;
      }
      upsellBanner_.Add(other.upsellBanner_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            upsellBanner_.AddEntriesFrom(input, _repeated_upsellBanner_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            upsellBanner_.AddEntriesFrom(ref input, _repeated_upsellBanner_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class UpsellBanner : pb::IMessage<UpsellBanner>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpsellBanner> _parser = new pb::MessageParser<UpsellBanner>(() => new UpsellBanner());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<UpsellBanner> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Upsell.UpsellReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpsellBanner() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpsellBanner(UpsellBanner other) : this() {
      bannerId_ = other.bannerId_;
      bannerOkAction_ = other.bannerOkAction_;
      bannerOkButton_ = other.bannerOkButton_;
      bannerCancelAction_ = other.bannerCancelAction_;
      bannerCancelButton_ = other.bannerCancelButton_;
      bannerMessage_ = other.bannerMessage_;
      locale_ = other.locale_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public UpsellBanner Clone() {
      return new UpsellBanner(this);
    }

    /// <summary>Field number for the "banner_id" field.</summary>
    public const int BannerIdFieldNumber = 1;
    private int bannerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BannerId {
      get { return bannerId_; }
      set {
        bannerId_ = value;
      }
    }

    /// <summary>Field number for the "banner_ok_action" field.</summary>
    public const int BannerOkActionFieldNumber = 2;
    private string bannerOkAction_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BannerOkAction {
      get { return bannerOkAction_; }
      set {
        bannerOkAction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "banner_ok_button" field.</summary>
    public const int BannerOkButtonFieldNumber = 3;
    private string bannerOkButton_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BannerOkButton {
      get { return bannerOkButton_; }
      set {
        bannerOkButton_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "banner_cancel_action" field.</summary>
    public const int BannerCancelActionFieldNumber = 4;
    private string bannerCancelAction_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BannerCancelAction {
      get { return bannerCancelAction_; }
      set {
        bannerCancelAction_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "banner_cancel_button" field.</summary>
    public const int BannerCancelButtonFieldNumber = 5;
    private string bannerCancelButton_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BannerCancelButton {
      get { return bannerCancelButton_; }
      set {
        bannerCancelButton_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "banner_message" field.</summary>
    public const int BannerMessageFieldNumber = 6;
    private string bannerMessage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BannerMessage {
      get { return bannerMessage_; }
      set {
        bannerMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "locale" field.</summary>
    public const int LocaleFieldNumber = 7;
    private string locale_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Locale {
      get { return locale_; }
      set {
        locale_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as UpsellBanner);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(UpsellBanner other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BannerId != other.BannerId) return false;
      if (BannerOkAction != other.BannerOkAction) return false;
      if (BannerOkButton != other.BannerOkButton) return false;
      if (BannerCancelAction != other.BannerCancelAction) return false;
      if (BannerCancelButton != other.BannerCancelButton) return false;
      if (BannerMessage != other.BannerMessage) return false;
      if (Locale != other.Locale) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BannerId != 0) hash ^= BannerId.GetHashCode();
      if (BannerOkAction.Length != 0) hash ^= BannerOkAction.GetHashCode();
      if (BannerOkButton.Length != 0) hash ^= BannerOkButton.GetHashCode();
      if (BannerCancelAction.Length != 0) hash ^= BannerCancelAction.GetHashCode();
      if (BannerCancelButton.Length != 0) hash ^= BannerCancelButton.GetHashCode();
      if (BannerMessage.Length != 0) hash ^= BannerMessage.GetHashCode();
      if (Locale.Length != 0) hash ^= Locale.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BannerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BannerId);
      }
      if (BannerOkAction.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BannerOkAction);
      }
      if (BannerOkButton.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BannerOkButton);
      }
      if (BannerCancelAction.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(BannerCancelAction);
      }
      if (BannerCancelButton.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BannerCancelButton);
      }
      if (BannerMessage.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(BannerMessage);
      }
      if (Locale.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Locale);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BannerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(BannerId);
      }
      if (BannerOkAction.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BannerOkAction);
      }
      if (BannerOkButton.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(BannerOkButton);
      }
      if (BannerCancelAction.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(BannerCancelAction);
      }
      if (BannerCancelButton.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(BannerCancelButton);
      }
      if (BannerMessage.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(BannerMessage);
      }
      if (Locale.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Locale);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BannerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BannerId);
      }
      if (BannerOkAction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BannerOkAction);
      }
      if (BannerOkButton.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BannerOkButton);
      }
      if (BannerCancelAction.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BannerCancelAction);
      }
      if (BannerCancelButton.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BannerCancelButton);
      }
      if (BannerMessage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BannerMessage);
      }
      if (Locale.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Locale);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(UpsellBanner other) {
      if (other == null) {
        return;
      }
      if (other.BannerId != 0) {
        BannerId = other.BannerId;
      }
      if (other.BannerOkAction.Length != 0) {
        BannerOkAction = other.BannerOkAction;
      }
      if (other.BannerOkButton.Length != 0) {
        BannerOkButton = other.BannerOkButton;
      }
      if (other.BannerCancelAction.Length != 0) {
        BannerCancelAction = other.BannerCancelAction;
      }
      if (other.BannerCancelButton.Length != 0) {
        BannerCancelButton = other.BannerCancelButton;
      }
      if (other.BannerMessage.Length != 0) {
        BannerMessage = other.BannerMessage;
      }
      if (other.Locale.Length != 0) {
        Locale = other.Locale;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BannerId = input.ReadInt32();
            break;
          }
          case 18: {
            BannerOkAction = input.ReadString();
            break;
          }
          case 26: {
            BannerOkButton = input.ReadString();
            break;
          }
          case 34: {
            BannerCancelAction = input.ReadString();
            break;
          }
          case 42: {
            BannerCancelButton = input.ReadString();
            break;
          }
          case 50: {
            BannerMessage = input.ReadString();
            break;
          }
          case 58: {
            Locale = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BannerId = input.ReadInt32();
            break;
          }
          case 18: {
            BannerOkAction = input.ReadString();
            break;
          }
          case 26: {
            BannerOkButton = input.ReadString();
            break;
          }
          case 34: {
            BannerCancelAction = input.ReadString();
            break;
          }
          case 42: {
            BannerCancelButton = input.ReadString();
            break;
          }
          case 50: {
            BannerMessage = input.ReadString();
            break;
          }
          case 58: {
            Locale = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
