name: Build Keeper SDK for .NET

on: 
#  push:
#    branches: 
#      - 'release_*'
  workflow_dispatch:
  

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Setup product versions
        run: |
          $ErrorView = 'NormalView'
          $branch = ($Env:GITHUB_REF -split '/')[2] 
          $comp = $branch -split '_'
          $sdkVersion = $comp[1]
          $packageVersion = $sdkVersion
          if ($comp[2]) {
            $packageVersion = $packageVersion + '-' + $comp[2]
          }

          $buildVersion = $sdkVersion + '.' + $Env:GITHUB_RUN_NUMBER

          echo "SDK_VERSION=${sdkVersion}" >> $Env:GITHUB_ENV
          echo "PACKAGE_VERSION=${packageVersion}" >> $Env:GITHUB_ENV
          echo "BUILD_VERSION=${buildVersion}" >> $Env:GITHUB_ENV
        shell: powershell      

      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
         dotnet-version: 5.0.x
      - uses: microsoft/setup-msbuild@v1.0.2
      
      - uses: nuget/setup-nuget@v1
      - run: nuget restore KeeperSdk.sln


      - name: Load signing certificate
        run: |
          if (Test-Path -Path certificate.txt) { Remove-Item certificate.txt }
          if (Test-Path -Path certificate.pfx) { Remove-Item certificate.pfx }
          Set-Content -Path certificate.txt -Value '${{ secrets.PFX_CERT }}'
          certutil -decode certificate.txt certificate.pfx
          Remove-Item certificate.txt
        shell: powershell

      - name: Build Keeper SDK Nuget package
        working-directory: ./KeeperSdk
        run: |
          if (Test-Path bin) { Remove-Item -Force -Recurse bin }
          dotnet restore /P:Configuration=Release
          dotnet clean /P:Configuration=Release
          dotnet build /P:Configuration=Release /P:Version=${Env:SDK_VERSION} /P:AssemblyVersion=${Env:BUILD_VERSION} /P:FileVersion=${Env:BUILD_VERSION}
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /f ..\certificate.pfx /t "http://timestamp.digicert.com" /v /p "${{ secrets.PFX_PASS }}" /d ".NET Keeper SDK" "bin\Release\net452\KeeperSdk.dll"
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /f ..\certificate.pfx /t "http://timestamp.digicert.com" /v /p "${{ secrets.PFX_PASS }}" /d ".NET Keeper SDK" "bin\Release\netstandard2.0\KeeperSdk.dll"
          dotnet pack --no-build --no-restore /P:Configuration=Release /P:Version=${Env:PACKAGE_VERSION} /P:IncludeSymbols=true /P:SymbolPackageFormat=snupkg
        shell: powershell      

      - name: Build Security Key library for Windows
        working-directory: ./WinWebAuthn
        run: |
          if (Test-Path bin) { Remove-Item -Force -Recurse bin }
          msbuild /T:Restore,Clean /P:Configuration=Release
          msbuild /T:Build /P:Configuration=Release /P:Version=${Env:SDK_VERSION} /P:AssemblyVersion=${Env:BUILD_VERSION} /P:FileVersion=${Env:BUILD_VERSION}
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /f ..\certificate.pfx /t "http://timestamp.digicert.com" /v /p "${{ secrets.PFX_PASS }}" /d ".NET Keeper SDK" "bin\Release\WinWebAuthn.dll"
        shell: powershell

      - name: Build .Net Commander
        working-directory: ./Commander
        run: |
          if (Test-Path bin) { Remove-Item -Force -Recurse bin }
          msbuild /T:Restore,Clean /P:Configuration=Release
          msbuild /T:Build /P:Configuration=Release /P:Version=${Env:SDK_VERSION} /P:AssemblyVersion=${Env:BUILD_VERSION} /P:FileVersion=${Env:BUILD_VERSION}
          & 'C:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe' sign /f ..\certificate.pfx /t "http://timestamp.digicert.com" /v /p "${{ secrets.PFX_PASS }}" /d ".NET Keeper SDK" "bin\Release\Commander.exe"
        shell: powershell      

      - name: Zip Commander
        run: |
          $params = @{
            Path = "Commander/bin/Release/Commander.*", "Commander/bin/Release/CommandLine.dll", "WinWebAuthn/bin/Release/WinWebAuthn.dll", "KeeperSdk/bin/Release/net452/*.dll"
            CompressionLevel = "Fastest"
            DestinationPath = "Commander-${Env:PACKAGE_VERSION}.zip"
          }
          Compress-Archive @params
        shell: powershell

      - name: Store SDK Nuget artifacts
        uses: actions/upload-artifact@v2
        with:
          name: KeeperSdk-${{ env.PACKAGE_VERSION }}-Nuget-Package
          path: |
            KeeperSdk/bin/Release/Keeper.Sdk.${{ env.PACKAGE_VERSION }}.nupkg
            KeeperSdk/bin/Release/Keeper.Sdk.${{ env.PACKAGE_VERSION }}.snupkg
          retention-days: 1

      - name: Store Commander artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Commander-${{ env.PACKAGE_VERSION }}
          path: Commander-${{ env.PACKAGE_VERSION }}.zip
          retention-days: 1
